name: plastic
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.4
  - cudatoolkit=11.6
  - torchaudio=0.12.0
  - pytorch=1.12.0
  - torchvision=0.13.0
  - pandas=1.4.3
  - tqdm=4.64.0
  - matplotlib=3.5.1
  - h5py=3.6.0
